gender_related_terms = [
    "woman", "women", "female", "gender", "emancipation", "pink", "quota", "equality",
    "equity", "feminism", "feminist", "motherhood", "reproductive", "sexual", "work-life",
    "workforce", "pay gap", "glass ceiling", "harassment", "discrimination", "empowerment",
    "parity", "inclusion", "diversity", "mentor", "caregiver", "patriarchy", "stereotype",
    "bias", "intersectionality", "advocate", "leader", "boss", "representation", "domestic",
    "trafficking", "violence", "assault", "victim", "survivor", "maternity", "childcare",
    "caregiving", "co-worker", "workplace", "sexism", "abuse", "support", "rights",
    "girl", "daughter", "sister", "wife", "aunt", "grandmother", "queen", "goddess", "matriarch",
    "dame", "diva", "lady", "bachelorette", "housewife", "nurse", "widow", "virgin", "bride",
    "girlfriend", "fiancée", "mistress", "crone", "heroine", "matron", "barrister", "nanny",
    "maiden", "senior", "chick", "babe", "madam", "mademoiselle", "vixen", "helpmate", "mama",
    "youngster", "gal", "fashionista", "militant", "veteran", "tomboy", "volunteer", "protagonist",
    "guardian", "champion", "celebrity", "entrepreneur", "vanguard", "scholar", "author", "artist",
    "pioneer", "executive", "educator", "scientist", "activist", "philanthropist", "reformer",
    "trailblazer", "rebel", "innovator", "maverick", "visionary", "ambassador", "orator", "philosopher",
    "strategist", "rolemodel", "campaigner", "organizer", "muse", "warrior", "consultant", "coach",
    "therapist", "explorer", "inventor", "counselor", "socialite", "influencer", "man", "men",
    "male", "boy", "father", "son", "brother", "husband", "uncle", "grandfather", "king", "hero",
    "gentleman", "dude", "groom", "fiancé", "bachelor", "patriarch", "baron", "lord", "master",
    "guy", "chap", "buddie", "mister", "sir", "stud", "handsome", "macho", "alpha", "expert",
    "heroic"
]

climate_related_terms = [
    'exchange', 'service', 'benchmark', 'organization', 'regulation', 'methodology', 'planning', 'evaluation',
    'consistency', 'tool', 'resilience', 'output', 'scientific', 'consultation', 'equity', 'preparedness', 'safeguard',
    'system', 'value', 'return', 'capacity', 'technology', 'continuity', 'community', 'tourism', 'leadership', 'design',
    'project', 'coalition', 'plan', 'information', 'reporting', 'carbon', 'sector', 'guideline', 'government',
    'festivals', 'justice', 'spaces', 'study', 'initiative', 'aspiration', 'environmental', 'trading', 'urbanism',
    'response', 'global', 'action', 'finance', 'stewardship', 'dividend', 'campaign', 'outreach', 'effectiveness',
    'drought', 'vulnerability', 'reconstruction', 'interaction', 'international', 'greenhouse', 'geothermal', 'data',
    'agriculture', 'model', 'energy', 'practices', 'cultural', 'solution', 'partnership', 'efficacy', 'sensitivity',
    'network', 'recycling', 'goal', 'economic', 'diversity', 'transport', 'knowledge', 'bioenergy', 'movement',
    'coastal', 'dissemination', 'risk', 'collaboration', 'investment', 'civil', 'protocol', 'approach', 'impact',
    'industrial', 'sustainability', 'sponsorship', 'weather', 'objective', 'biodiversity', 'architecture', 'wind',
    'framework', 'benefit', 'transportation', 'analysis', 'input', 'livelihoods', 'recovery', 'waste', 'adaptation',
    'eco', 'grant', 'support', 'contribution', 'monitoring', 'public', 'business', 'communication', 'funding',
    'procedure', 'national', 'renewable', 'research', 'access', 'restoration', 'flood', 'success', 'zero-waste',
    'society', 'advocacy', 'wellbeing', 'feedback', 'corporate', 'philanthropy', 'expense', 'implementation', 'local',
    'capital', 'innovation', 'gases', 'heritage', 'review', 'responsibility', 'policy', 'efficiency', 'stability',
    'solar', 'profit', 'resource', 'strategy', 'management', 'pollution', 'social', 'integration', 'offset',
    'expertise', 'operation', 'process', 'assessment', 'adaptability', 'arts', 'natural', 'standard', 'criterion',
    'collaborative', 'emission', 'temperature', 'private', 'emergency', 'awareness', 'quality', 'engagement',
    'consumption', 'hydro', 'low-carbon', 'empowerment', 'mission', 'durability', 'infrastructure', 'preservation',
    'upcycling', 'jobs', 'mitigation', 'yield', 'activity', 'neutral', 'inclusivity', 'circular', 'disaster',
    'industry', 'communities', 'climate', 'performance', 'conservation', 'regional', 'eco-friendly', 'vision', 'cost',
    'program', 'flexibility', 'education', 'literacy', 'reduction', 'precipitation', 'green', 'audit', 'technical'
]

economic_reform_terms = [
    'fiscal', 'alignment', 'liberalization', 'competitive', 'healthcare', 'development', 'framework', 'effectiveness',
    'stimulus', 'standard', 'frameworks', 'interest', 'system', 'transformation', 'devaluation', 'expansion', 'resilience',
    'debt', 'reviews', 'initiative', 'initiatives', 'sustainable', 'advancement', 'rebalancing', 'banking', 'sector',
    'urbanization', 'incentives', 'visions', 'tax', 'transparency', 'public', 'revaluation', 'legal', 'infrastructure',
    'benchmarking', 'delivery', 'trends', 'instruments', 'accountability', 'engagement', 'oversight', 'industrial',
    'deregulation', 'systems', 'reform', 'institutional', 'targets', 'exchange', 'contract', 'administration',
    'planning', 'cost', 'value-added', 'priorities', 'sustainability', 'market', 'savings', 'control', 'review',
    'financial', 'approaches', 'evaluation', 'government', 'guidelines', 'adaptation', 'subsidization', 'education',
    'challenges', 'realignment', 'labor', 'mechanisms', 'openness', 'enhancements', 'stabilization', 'intervention',
    'resources', 'inflation', 'efficacy', 'export', 'policy-making', 'regulatory', 'diversification', 'approach',
    'trade', 'investment', 'budget', 'revenue', 'solutions', 'privatization', 'climate', 'price', 'macroeconomic',
    'property', 'restructuring', 'credit', 'enforcement', 'performance', 'strategy', 'standardization', 'recovery',
    'policies', 'business', 'adjustment', 'balance', 'governance', 'efficiency', 'focus', 'innovation', 'benchmark',
    'growth', 'standards', 'foreign', 'stability', 'strategic', 'capital', 'pricing', 'entrepreneurship', 'regulation',
    'allocation', 'analysis', 'welfare', 'social', 'monitoring', 'contraction', 'partnership', 'regional',
    'redistribution', 'resource', 'structure', 'monetary', 'pension', 'job', 'implementation', 'revision', 'outcomes',
    'poverty', 'import', 'compliance', 'employment', 'optimization', 'subsidy', 'management', 'income', 'regulations',
    'efforts', 'integration', 'process', 'enhancement', 'strategies', 'actions', 'policy', 'corporate', 'inclusion',
    'alleviation', 'agreements', 'assessment', 'guidance', 'rural'
]

social_policy_terms = [
    'wellbeing', 'cohesion', 'housing', 'healthcare', 'improvement', 'integration', 'health', 'access', 'reform',
    'involvement', 'mobility', 'justice', 'equality', 'economic', 'community', 'equity', 'prosperity', 'growth',
    'income', 'infrastructure', 'participation', 'redistribution', 'safety', 'market', 'protection', 'efficiency',
    'intervention', 'adjustment', 'affordability', 'welfare', 'employment', 'support', 'engagement', 'resources',
    'service', 'advocacy', 'enhancement', 'priorities', 'policy', 'assistance', 'transformation', 'stability',
    'poverty', 'care', 'mentorship', 'benefit', 'accessibility', 'advancement', 'coverage', 'investment', 'opportunity',
    'inclusion', 'education', 'programs', 'skills', 'balancing', 'entrepreneurship', 'capital', 'quality', 'security',
    'subsidies', 'mentoring', 'reduction', 'diversification', 'benefits', 'socialization', 'representation',
    'sustainability', 'training', 'upliftment', 'development', 'resilience', 'diversity', 'innovation', 'empowerment'
]

environmental_policy_terms = [
    'capture', 'upcycle', 'efficacy', 'toxin', 'disaster', 'consistency', 'safeguard', 'sponsorship', 'cleanup',
    'response', 'coastal', 'communication', 'national', 'communities', 'literacy', 'dividend', 'temperature',
    'quarantine', 'circulation', 'practices', 'incinerate', 'industrial', 'profit', 'colloid', 'boreal', 'organization',
    'capital', 'contaminant', 'dissemination', 'circular', 'evolution', 'regional', 'initiative', 'evaluation',
    'continuity', 'goal', 'flora', 'vulnerability', 'equity', 'resilience', 'agriculture', 'justice',
    'phytoremediation', 'empowerment', 'solar', 'local', 'carbon', 'irrigation', 'cultural', 'eco', 'audit', 'ocean',
    'integration', 'species', 'sanitation', 'leadership', 'action', 'yield', 'innovation', 'sequestration', 'organic',
    'sustainability', 'wellness', 'compost', 'absorb', 'model', 'incubation', 'drought', 'xeriscape', 'service',
    'expertise', 'movement', 'sequester', 'responsibility', 'diversity', 'philanthropy', 'particulate', 'virus',
    'coalition', 'business', 'watershed', 'naturalism', 'system', 'finance', 'scientific', 'natural', 'spaces', 'alga',
    'freshwater', 'preserve', 'preparedness', 'international', 'architecture', 'review', 'funding', 'silt', 'cost',
    'livelihoods', 'protocol', 'jobs', 'vegetate', 'weather', 'greenery', 'corporate', 'remediate', 'wind',
    'effectiveness', 'festivals', 'feedback', 'expense', 'terrestrial', 'transform', 'precipitation', 'water',
    'microbe', 'consultation', 'procedure', 'desertification', 'sink', 'program', 'litter', 'input', 'galvanization',
    'analysis', 'inclusivity', 'salinity', 'upcycling', 'capacity', 'mission', 'plan', 'partnership', 'urbanism',
    'herbicide', 'pollutant', 'waste', 'gas', 'sanitize', 'tool', 'global', 'biodiversity', 'energy', 'investment',
    'afforestation', 'zeolite', 'heritage', 'cultivation', 'strategy', 'solution', 'urbanization', 'evapotranspiration',
    'guideline', 'trading', 'access', 'assessment', 'study', 'data', 'infest', 'reconstruction', 'standard',
    'information', 'degradation', 'adaptability', 'awareness', 'policy', 'exchange', 'stability', 'management',
    'contribution', 'biofuel', 'consumption', 'durability', 'air', 'reporting', 'private', 'arts', 'legume',
    'criterion', 'gases', 'output', 'benefit', 'grant', 'carbonic', 'safety', 'operation', 'aspiration', 'approach',
    'transport', 'methodology', 'impact', 'nutrient', 'civil', 'industry', 'society', 'emergency', 'amendment',
    'riparian', 'green', 'benchmark', 'co2', 'hazard', 'collaboration', 'sector', 'framework', 'recovery', 'success',
    'flood', 'nuclear', 'homeostasis', 'technology', 'performance', 'public', 'decarbonize', 'project', 'biomass',
    'implementation', 'recycling', 'transportation', 'leakage', 'cellulose', 'fossil', 'geothermal', 'infiltration',
    'government', 'resource', 'process', 'microorganism', 'collaborative', 'preservation', 'erosion', 'monitoring',
    'support', 'vision', 'engagement', 'network', 'degradable', 'sensitivity', 'neutral', 'education', 'technical',
    'design', 'knowledge', 'greenhouse', 'oxygen', 'activity', 'reduce', 'outreach', 'coral', 'fungus', 'community',
    'risk', 'incineration', 'research', 'flexibility', 'density', 'paradigm', 'climate', 'adaptation', 'planning',
    'efficiency', 'biodegrade', 'extraction', 'mitigation', 'bacterium', 'filter', 'utilize', 'low-carbon',
    'regulation', 'reclamation', 'bioenergy', 'habitat', 'conservation', 'stewardship', 'sustain', 'social', 'zero',
    'reforestation', 'balance', 'renewable', 'environment', 'wellbeing', 'ecosystem', 'restoration', 'inoculate',
    'offset', 'invasive', 'marine', 'evaporation', 'forestation', 'sediment', 'vegetation', 'adverse', 'value', 'decay',
    'advocacy', 'objective', 'emission', 'interaction', 'quality', 'transparency', 'tourism', 'campaign', 'nitrogen',
    'return', 'extract', 'legislation', 'abundance'
]
